---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable
  code_climate:
    repo_token:
      secure: "k4wbZZ5Rh2h7ZnMl0Njax86WPo1KAXBCRQwMdLZiRsZ0fDIBlTN69xwRXqVanbZUP30Nq8T3OvSwilJl1OBZS/et6hSZZmQXjkE05YBXvgKMheU/mtqvQW0dkYC29AYsXHbJpVMNfZiR6T0z95wGZSO08zwiA0upFGnOMPGj7kuQiq1qBNcQF8qzQ5z1IUV3Mq4wo5QvS+VaAQt0eBTXBr9hkIS7Nosq0AO/33q0gnm6glGnl68oSNpp4CO4uHRfK83dsaHW4UvbEEOEKes3HgwyDnUudecL+Yniask7ojIC0HLm9Bhg83D5sO2FburD00ZAi0EPW1KjjnxwvqEuuQZ5UT/2zMYwBi9EmHxsBmQReR2SFNMklG+nFB6hIWItW4LII3STyh7ZzP1dan6b83cGrsxO7r29ZyofwmOhToazu3+6D5VAhhDVX3tQqMYv8MHpF53u5rlAHbhaEajYJzfVpnY9M2VoZDUQMqU7hJfRnDOjFOswF7WImQFXzbNf1zAjhINhuw7vPyTiU9mEXFuZndHhxrAqt2GYoRp5OmoH6SgGedqiEf3FrXiydjduHVBAyniErt2myzeXvOC6aW5Dh4fNf83b4MBlw8IM4AbhGYqquE4Xi4nSGSyn5dEQR4ZY4ndFHHd3uyJNqC6Afj+4g32b82kakDspOb6TxKo="

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test

    - name: "Floating Dependencies"
      script:
        - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - COVERAGE=true node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
